@startuml

Abwasserbauwerk <|-- Kanal
Abwasserbauwerk <|-- Vorflutereinlauf
Abwasserbauwerk -- BauwerksTeil
Abwasserbauwerk <|-- Spezialbauwerk
Abwasserbauwerk <|-- Versickerungsanlage
Abwasserbauwerk -- Abwassernetzelement
Abwasserbauwerk <|-- Normschacht
Abwasserbauwerk -- AbwasserbauwerkText
Versickerungsanlage ..> Rohrprofil
Rohrprofil -- Haltung
Haltung -- HaltungText
Haltung -- HaltungsPunkt
Abwassernetzelement -- Haltung
Abwassernetzelement -- Abwasserknoten
BauwerksTeil <|-- Bankett
BauwerksTeil <|-- Trockenwetterfallrohr
BauwerksTeil <|-- Trockenwetterrinne
BauwerksTeil <|-- Deckel
BauwerksTeil <|-- Einstieghilfe


class Abwasserbauwerk {
OBJ_ID
Bezeichnung
}
class Abwassernetzelement {
OBJ_ID
Bezeichnung
}
class HaltungsPunkt {
OBJ_ID
Bezeichnung
}
class Rohrprofil {
OBJ_ID
Bezeichnung
}
class BauwerksTeil {
OBJ_ID
Bezeichnung
}
class AbwasserbauwerkText{
Textinhalt
TextPos
PlanTyp
}
class HaltungText{
Textinhalt
TextPos
PlanTyp
}

@enduml