@startuml
!include C4_Context.puml

title System Context diagram for GIS-to-BIM Converter Prototype

Person(user, "Protoype User", "An architect, civil engineer, etc. that wants to convert GeoPackage data to IFC 4.3 ")
System(GIS_To_BIM_Converter_Prototype, "GPKG-to-IFC CLI Prototype", "Allows users to enter arguments to convert GeoPackage data to IFC 4.3")
System_Ext(filesystem, "File System", "File system provided by the OS")

Rel(user, GIS_To_BIM_Converter_Prototype, "uses")
Rel(GIS_To_BIM_Converter_Prototype, filesystem, "writes to")

@enduml