@startuml

!include C4_Container.puml

title LKMap-to-IFC Converter Prototype - Container Diagram
Person(user, "Protoype User", "An architect, civil engineer, etc. that wants to convert LKMap_2025 data to IFC 4.3 ")

System_Boundary(system, "LKMap-to-IFC Prototype") {
    Container(cli, "Command Line Interface", "Python, Click", "Provides the CLI with required arguments and optionals")
    Container(model, "Model", "Python, Pyogrio", "Controls the process of extracting and preparing given data")
    Container(ifc, "IFC", "Python, IfcOpenShell", "Controls the process of creating the IFC file with the prepared data")
    ContainerDb(geoPackage, "GeoPackage", "SQLite Database", "Stores provided LKMap_2025 data to be converted")
    Rel(cli, model, "uses")
    Rel(cli, ifc, "uses")
    Rel(model, geoPackage, "uses")
}
System_Ext(filesystem, "File System", "The file system provided by the OS")
Rel(user, system, "uses")
Rel(ifc, filesystem, "writes to")

@enduml
