@startuml

!include C4_Container.puml

title LKMap-to-IFC Converter Prototype - Container Diagram
Person(user, "Protoype User", "An architect, civil engineer, etc. that wants to convert GeoPackage data to IFC 4.3 ")

System_Boundary(system, "LKMap-to-IFC Prototype") {
    Container(cli, "ConvertLKMap2IFC", "Python, Click", "Provides the CLI with required arguments and convert-gpkg-to-ifc command")
    Container(model, "Data Processing Chain", "Python, Pyogrio", "Controls the process of extrancting and preparing given data")
    Container(ifc, "Ifc Creation Controller", "Python, IfcOpenShell", "Controls the process of creating the IFC file")
    ContainerDb(geoPackage, "GeoPackage", "SQLite Database", "Stores provided 2D data to be converted")
    Rel(cli, model, "uses")
    Rel(cli, ifc, "uses")
    Rel(model, geoPackage, "uses")
}
System_Ext(filesystem, "File System", "The file system provided by the OS")
Rel(user, system, "uses")
Rel(ifc, filesystem, "writes to")

@enduml
