@startuml

!include C4_Container.puml

title GIS-to-BIM Converter Prototype - Container Diagram
Person(user, "Protoype User", "An architect, civil engineer, etc. that wants to convert GeoPackage data to IFC 4.3 ")

System_Boundary(system, "GPKG-to-IFC Prototype") {
    Container(cli, "Command Line Interface", "Python, Typer", "Provides the CLI with required arguments and convert-gpkg-to-ifc command")
    Container(controller, "Data Processing Controller", "Python", "Controls the processing of given data")
    Rel(cli, controller, "uses")
}
System_Ext(filesystem, "File System", "The file system provided by the OS")
ContainerDb(geoPackage, "GeoPackage", "SQLite Database", "Stores provided 2D data to be converted")

Rel(cli, geoPackage, "aquires dataset from argument")
Rel(geoPackage, controller, "loads dataset")
Rel(user, system, "uses")
Rel(controller, filesystem, "writes to")

@enduml
