@startuml
!include C4_Component.puml

title LKMap-to-IFC Converter Prototype - IFC Component Diagram

Container(cli, "ConvertLKMap2IFC", "Python, Click")
Container(modelController, "Model", "Python, Pyogrio, Subprocess")
Rel_L(cli, modelController, "Uses")
Rel(cli, IFC, "Uses")

Container_Boundary(IFC, "IFC") {
    Component(ifcCreationController, "IfcCreationController", "Python, IfcOpenShell")
    Component(ifcElementBuilders, "IfcElementBuilders", "Python, IfcOpenShell")
    Component(ifcProjectSetupBuilder, "IfcProjectSetupBuilder", "Python, IfcOpenShell")
    Component(ifcPropertySetBuilder, "IfcPropertySetBuilder", "Python, IfcOpenShell")
    Component(ifcUtils, "IfcUtils", "Python, IfcOpenShell")
    Rel(ifcCreationController, ifcElementBuilders, "uses")
    Rel(ifcCreationController, ifcProjectSetupBuilder, "uses")
    Rel(ifcCreationController, ifcUtils, "uses")
    Rel_L(ifcElementBuilders, ifcUtils, "uses")
    Rel(ifcProjectSetupBuilder, ifcUtils, "uses")
    Rel_R(ifcCreationController, ifcPropertySetBuilder, "uses")
}
System_Ext(filesystem, "File System")
ContainerDb(geoPackage, "GeoPackage", "SQLite Database")

Rel(modelController, geoPackage, "Uses")
Rel_R(cli, filesystem, "writes to")


@enduml
