@startuml
!include C4_Component.puml

title LKMap-to-IFC Converter Prototype - IFC Creation Controller Component Diagram

Container(cli, "ConvertLKMap2IFC", "Python, Click", "Provides the CLI with required arguments and options")
Container(modelController, "Data Processing Chain", "Python, Pyogrio, Subprocess", "Prepares the provided data")
ContainerDb(geoPackage, "GeoPackage", "SQLite Database", "Stores provided 2D data to be converted")
Rel_L(cli, modelController, "Uses")
Rel(cli, IFCCreationController, "Uses")

Container_Boundary(IFCCreationController, "IFC Creation Controller") {
    Component(ifcCreationController, "IfcCreationController", "Python, IfcOpenShell", "Controls the creation of elements in the IFC model")
    Component(ifcElementBuilders, "IfcElementBuilders", "Python, IfcOpenShell", "Creates Elements and their geometric representations")
    Component(ifcProjectSetupBuilder, "IfcProjectSetupBuilder", "Python, IfcOpenShell", "Creates the basic structure in the IFC model")
    Component(ifcPropertySetBuilder, "IfcPropertySetBuilder", "Python, IfcOpenShell", "Creates the IFC Property Sets for the elements")
    Component(ifcUtils, "IfcUtils", "Python, IfcOpenShell", "Provides utility functions")
    Rel(ifcCreationController, ifcElementBuilders, "uses")
    Rel(ifcCreationController, ifcProjectSetupBuilder, "uses")
    Rel(ifcCreationController, ifcUtils, "uses")
    Rel_L(ifcElementBuilders, ifcUtils, "uses")
    Rel(ifcProjectSetupBuilder, ifcUtils, "uses")
    Rel_R(ifcCreationController, ifcPropertySetBuilder, "uses")
}
System_Ext(filesystem, "File System", "The file system provided by the OS")
ContainerDb(geoPackage, "GeoPackage", "SQLite Database", "Stores provided LKMap_2025 data to be converted")

Rel(modelController, geoPackage, "Uses")
Rel_R(cli, filesystem, "writes to")


@enduml
