@startuml
!include C4_Component.puml

title LKMap-to-IFC Converter Prototype - Model Component Diagram

Container(cli, "ConvertLKMap2IFC", "Python, Click")

Container(ifcController, "IFC Creation Controller", "Python, IfcOpenShell")
ContainerDb(geoPackage, "GeoPackage", "SQLite Database")
Component_Ext(ili2gpkg, "Ili2GPKG", "java")

Rel_D(cli, Model, "Uses")
Rel_R(cli, ifcController, "Uses")
Container_Boundary(Model, "Model") {
    Component(dataProcessingChain, "Data Processing Chain", "Python")
    Component(coordinateAdapter, "Coordinate Adapter", "Python")
    Component(geometryProcessor, "Geometry Processor", "Python, Pyogrio")
    Component(geoPackageUtils, "GeoPackage Utils", "Python, Pyogrio, Subprocess")
    Component(tapPointProcessor, "Tapping Point Processor", "Python, Pyogrio")
    Component(toDictionaryProcessor, "GroupingToDictionaryProcessor", "Python, Pyogrio")
    Rel_R(dataProcessingChain, geometryProcessor, "uses")
    Rel_L(dataProcessingChain, tapPointProcessor, "uses")
    Rel(dataProcessingChain, geoPackageUtils, "uses")
    Rel(dataProcessingChain, coordinateAdapter, "uses")
    Rel(dataProcessingChain, toDictionaryProcessor, "uses")
}
Rel(geoPackageUtils, ili2gpkg, "uses")
System_Ext(filesystem, "File System")
ContainerDb(geoPackage, "GeoPackage", "SQLite Database")

Rel(Model, geoPackage, "Uses")
Rel_L(cli, filesystem, "writes to")


@enduml
