@startuml
'https://plantuml.com/use-case-diagram

actor Architect as a
actor "Civil Engineer" as ce
actor authorities as auth




package LKMAP-to-BIM-Converter-CLI {
  usecase "Input LKMAP-Data" as UC1
  usecase "View Height Insecurities" as UC2
  usecase "Export IFC4 File" as UC3
}

package Visualizer{
}

@enduml